// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/mindwell-server/models"
)

// GetUsersNameOKCode is the HTTP code returned for type GetUsersNameOK
const GetUsersNameOKCode int = 200

/*GetUsersNameOK User data

swagger:response getUsersNameOK
*/
type GetUsersNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewGetUsersNameOK creates GetUsersNameOK with default headers values
func NewGetUsersNameOK() *GetUsersNameOK {

	return &GetUsersNameOK{}
}

// WithPayload adds the payload to the get users name o k response
func (o *GetUsersNameOK) WithPayload(payload *models.Profile) *GetUsersNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users name o k response
func (o *GetUsersNameOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersNameNotFoundCode is the HTTP code returned for type GetUsersNameNotFound
const GetUsersNameNotFoundCode int = 404

/*GetUsersNameNotFound User not found

swagger:response getUsersNameNotFound
*/
type GetUsersNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUsersNameNotFound creates GetUsersNameNotFound with default headers values
func NewGetUsersNameNotFound() *GetUsersNameNotFound {

	return &GetUsersNameNotFound{}
}

// WithPayload adds the payload to the get users name not found response
func (o *GetUsersNameNotFound) WithPayload(payload *models.Error) *GetUsersNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users name not found response
func (o *GetUsersNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
