// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/mindwell-server/models"
)

// GetUsersNameImagesOKCode is the HTTP code returned for type GetUsersNameImagesOK
const GetUsersNameImagesOKCode int = 200

/*GetUsersNameImagesOK Image list

swagger:response getUsersNameImagesOK
*/
type GetUsersNameImagesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ImageList `json:"body,omitempty"`
}

// NewGetUsersNameImagesOK creates GetUsersNameImagesOK with default headers values
func NewGetUsersNameImagesOK() *GetUsersNameImagesOK {

	return &GetUsersNameImagesOK{}
}

// WithPayload adds the payload to the get users name images o k response
func (o *GetUsersNameImagesOK) WithPayload(payload *models.ImageList) *GetUsersNameImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users name images o k response
func (o *GetUsersNameImagesOK) SetPayload(payload *models.ImageList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersNameImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersNameImagesNotFoundCode is the HTTP code returned for type GetUsersNameImagesNotFound
const GetUsersNameImagesNotFoundCode int = 404

/*GetUsersNameImagesNotFound User not found

swagger:response getUsersNameImagesNotFound
*/
type GetUsersNameImagesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUsersNameImagesNotFound creates GetUsersNameImagesNotFound with default headers values
func NewGetUsersNameImagesNotFound() *GetUsersNameImagesNotFound {

	return &GetUsersNameImagesNotFound{}
}

// WithPayload adds the payload to the get users name images not found response
func (o *GetUsersNameImagesNotFound) WithPayload(payload *models.Error) *GetUsersNameImagesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users name images not found response
func (o *GetUsersNameImagesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersNameImagesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
