// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/mindwell-server/models"
)

// GetUsersNameFavoritesOKCode is the HTTP code returned for type GetUsersNameFavoritesOK
const GetUsersNameFavoritesOKCode int = 200

/*GetUsersNameFavoritesOK Entry list

swagger:response getUsersNameFavoritesOK
*/
type GetUsersNameFavoritesOK struct {

	/*
	  In: Body
	*/
	Payload *models.Feed `json:"body,omitempty"`
}

// NewGetUsersNameFavoritesOK creates GetUsersNameFavoritesOK with default headers values
func NewGetUsersNameFavoritesOK() *GetUsersNameFavoritesOK {

	return &GetUsersNameFavoritesOK{}
}

// WithPayload adds the payload to the get users name favorites o k response
func (o *GetUsersNameFavoritesOK) WithPayload(payload *models.Feed) *GetUsersNameFavoritesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users name favorites o k response
func (o *GetUsersNameFavoritesOK) SetPayload(payload *models.Feed) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersNameFavoritesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersNameFavoritesNotFoundCode is the HTTP code returned for type GetUsersNameFavoritesNotFound
const GetUsersNameFavoritesNotFoundCode int = 404

/*GetUsersNameFavoritesNotFound User not found

swagger:response getUsersNameFavoritesNotFound
*/
type GetUsersNameFavoritesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUsersNameFavoritesNotFound creates GetUsersNameFavoritesNotFound with default headers values
func NewGetUsersNameFavoritesNotFound() *GetUsersNameFavoritesNotFound {

	return &GetUsersNameFavoritesNotFound{}
}

// WithPayload adds the payload to the get users name favorites not found response
func (o *GetUsersNameFavoritesNotFound) WithPayload(payload *models.Error) *GetUsersNameFavoritesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users name favorites not found response
func (o *GetUsersNameFavoritesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersNameFavoritesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
