// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/mindwell-server/models"
)

// GetNotificationsIDOKCode is the HTTP code returned for type GetNotificationsIDOK
const GetNotificationsIDOKCode int = 200

/*GetNotificationsIDOK notification

swagger:response getNotificationsIdOK
*/
type GetNotificationsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Notification `json:"body,omitempty"`
}

// NewGetNotificationsIDOK creates GetNotificationsIDOK with default headers values
func NewGetNotificationsIDOK() *GetNotificationsIDOK {

	return &GetNotificationsIDOK{}
}

// WithPayload adds the payload to the get notifications Id o k response
func (o *GetNotificationsIDOK) WithPayload(payload *models.Notification) *GetNotificationsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get notifications Id o k response
func (o *GetNotificationsIDOK) SetPayload(payload *models.Notification) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNotificationsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNotificationsIDNotFoundCode is the HTTP code returned for type GetNotificationsIDNotFound
const GetNotificationsIDNotFoundCode int = 404

/*GetNotificationsIDNotFound not found

swagger:response getNotificationsIdNotFound
*/
type GetNotificationsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNotificationsIDNotFound creates GetNotificationsIDNotFound with default headers values
func NewGetNotificationsIDNotFound() *GetNotificationsIDNotFound {

	return &GetNotificationsIDNotFound{}
}

// WithPayload adds the payload to the get notifications Id not found response
func (o *GetNotificationsIDNotFound) WithPayload(payload *models.Error) *GetNotificationsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get notifications Id not found response
func (o *GetNotificationsIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNotificationsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
