// Code generated by go-swagger; DO NOT EDIT.

package entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	models "github.com/sevings/mindwell-server/models"
)

// GetEntriesBestHandlerFunc turns a function with the right signature into a get entries best handler
type GetEntriesBestHandlerFunc func(GetEntriesBestParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEntriesBestHandlerFunc) Handle(params GetEntriesBestParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// GetEntriesBestHandler interface for that can handle valid get entries best params
type GetEntriesBestHandler interface {
	Handle(GetEntriesBestParams, *models.UserID) middleware.Responder
}

// NewGetEntriesBest creates a new http.Handler for the get entries best operation
func NewGetEntriesBest(ctx *middleware.Context, handler GetEntriesBestHandler) *GetEntriesBest {
	return &GetEntriesBest{Context: ctx, Handler: handler}
}

/*GetEntriesBest swagger:route GET /entries/best entries getEntriesBest

GetEntriesBest get entries best API

*/
type GetEntriesBest struct {
	Context *middleware.Context
	Handler GetEntriesBestHandler
}

func (o *GetEntriesBest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEntriesBestParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
