// Code generated by go-swagger; DO NOT EDIT.

package entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/sevings/yummy-server/models"
)

// GetEntriesUsersMeFavoritesHandlerFunc turns a function with the right signature into a get entries users me favorites handler
type GetEntriesUsersMeFavoritesHandlerFunc func(GetEntriesUsersMeFavoritesParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEntriesUsersMeFavoritesHandlerFunc) Handle(params GetEntriesUsersMeFavoritesParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// GetEntriesUsersMeFavoritesHandler interface for that can handle valid get entries users me favorites params
type GetEntriesUsersMeFavoritesHandler interface {
	Handle(GetEntriesUsersMeFavoritesParams, *models.UserID) middleware.Responder
}

// NewGetEntriesUsersMeFavorites creates a new http.Handler for the get entries users me favorites operation
func NewGetEntriesUsersMeFavorites(ctx *middleware.Context, handler GetEntriesUsersMeFavoritesHandler) *GetEntriesUsersMeFavorites {
	return &GetEntriesUsersMeFavorites{Context: ctx, Handler: handler}
}

/*GetEntriesUsersMeFavorites swagger:route GET /entries/users/me/favorites entries getEntriesUsersMeFavorites

GetEntriesUsersMeFavorites get entries users me favorites API

*/
type GetEntriesUsersMeFavorites struct {
	Context *middleware.Context
	Handler GetEntriesUsersMeFavoritesHandler
}

func (o *GetEntriesUsersMeFavorites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEntriesUsersMeFavoritesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
