// Code generated by go-swagger; DO NOT EDIT.

package entries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/sevings/mindwell-server/models"
)

// GetEntriesMeWatchingHandlerFunc turns a function with the right signature into a get entries me watching handler
type GetEntriesMeWatchingHandlerFunc func(GetEntriesMeWatchingParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEntriesMeWatchingHandlerFunc) Handle(params GetEntriesMeWatchingParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// GetEntriesMeWatchingHandler interface for that can handle valid get entries me watching params
type GetEntriesMeWatchingHandler interface {
	Handle(GetEntriesMeWatchingParams, *models.UserID) middleware.Responder
}

// NewGetEntriesMeWatching creates a new http.Handler for the get entries me watching operation
func NewGetEntriesMeWatching(ctx *middleware.Context, handler GetEntriesMeWatchingHandler) *GetEntriesMeWatching {
	return &GetEntriesMeWatching{Context: ctx, Handler: handler}
}

/*GetEntriesMeWatching swagger:route GET /entries/me/watching entries getEntriesMeWatching

GetEntriesMeWatching get entries me watching API

*/
type GetEntriesMeWatching struct {
	Context *middleware.Context
	Handler GetEntriesMeWatchingHandler
}

func (o *GetEntriesMeWatching) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEntriesMeWatchingParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
