// Code generated by go-swagger; DO NOT EDIT.

package relations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/sevings/yummy-server/models"
)

// PutRelationsFromIDHandlerFunc turns a function with the right signature into a put relations from ID handler
type PutRelationsFromIDHandlerFunc func(PutRelationsFromIDParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn PutRelationsFromIDHandlerFunc) Handle(params PutRelationsFromIDParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// PutRelationsFromIDHandler interface for that can handle valid put relations from ID params
type PutRelationsFromIDHandler interface {
	Handle(PutRelationsFromIDParams, *models.UserID) middleware.Responder
}

// NewPutRelationsFromID creates a new http.Handler for the put relations from ID operation
func NewPutRelationsFromID(ctx *middleware.Context, handler PutRelationsFromIDHandler) *PutRelationsFromID {
	return &PutRelationsFromID{Context: ctx, Handler: handler}
}

/*PutRelationsFromID swagger:route PUT /relations/from/{id} relations putRelationsFromId

permit the user to follow you

*/
type PutRelationsFromID struct {
	Context *middleware.Context
	Handler PutRelationsFromIDHandler
}

func (o *PutRelationsFromID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutRelationsFromIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
