// Code generated by go-swagger; DO NOT EDIT.

package relations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/sevings/mindwell-server/models"
)

// PutRelationsToNameHandlerFunc turns a function with the right signature into a put relations to name handler
type PutRelationsToNameHandlerFunc func(PutRelationsToNameParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn PutRelationsToNameHandlerFunc) Handle(params PutRelationsToNameParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// PutRelationsToNameHandler interface for that can handle valid put relations to name params
type PutRelationsToNameHandler interface {
	Handle(PutRelationsToNameParams, *models.UserID) middleware.Responder
}

// NewPutRelationsToName creates a new http.Handler for the put relations to name operation
func NewPutRelationsToName(ctx *middleware.Context, handler PutRelationsToNameHandler) *PutRelationsToName {
	return &PutRelationsToName{Context: ctx, Handler: handler}
}

/*PutRelationsToName swagger:route PUT /relations/to/{name} relations putRelationsToName

PutRelationsToName put relations to name API

*/
type PutRelationsToName struct {
	Context *middleware.Context
	Handler PutRelationsToNameHandler
}

func (o *PutRelationsToName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutRelationsToNameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
