// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetOauth2AuthParams creates a new GetOauth2AuthParams object
// with the default values initialized.
func NewGetOauth2AuthParams() GetOauth2AuthParams {

	var (
		// initialize parameters with default values

		scopeDefault = string("read")
	)

	return GetOauth2AuthParams{
		Scope: &scopeDefault,
	}
}

// GetOauth2AuthParams contains all the bound params for the get oauth2 auth operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetOauth2Auth
type GetOauth2AuthParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	ClientID string
	/*
	  In: query
	*/
	CodeChallenge *string
	/*
	  In: query
	*/
	CodeChallengeMethod *string
	/*
	  Required: true
	  In: query
	*/
	RedirectURI string
	/*
	  Required: true
	  In: query
	*/
	ResponseType string
	/*
	  In: query
	  Default: "read"
	*/
	Scope *string
	/*
	  In: query
	*/
	State *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetOauth2AuthParams() beforehand.
func (o *GetOauth2AuthParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qClientID, qhkClientID, _ := qs.GetOK("client_id")
	if err := o.bindClientID(qClientID, qhkClientID, route.Formats); err != nil {
		res = append(res, err)
	}

	qCodeChallenge, qhkCodeChallenge, _ := qs.GetOK("code_challenge")
	if err := o.bindCodeChallenge(qCodeChallenge, qhkCodeChallenge, route.Formats); err != nil {
		res = append(res, err)
	}

	qCodeChallengeMethod, qhkCodeChallengeMethod, _ := qs.GetOK("code_challenge_method")
	if err := o.bindCodeChallengeMethod(qCodeChallengeMethod, qhkCodeChallengeMethod, route.Formats); err != nil {
		res = append(res, err)
	}

	qRedirectURI, qhkRedirectURI, _ := qs.GetOK("redirect_uri")
	if err := o.bindRedirectURI(qRedirectURI, qhkRedirectURI, route.Formats); err != nil {
		res = append(res, err)
	}

	qResponseType, qhkResponseType, _ := qs.GetOK("response_type")
	if err := o.bindResponseType(qResponseType, qhkResponseType, route.Formats); err != nil {
		res = append(res, err)
	}

	qScope, qhkScope, _ := qs.GetOK("scope")
	if err := o.bindScope(qScope, qhkScope, route.Formats); err != nil {
		res = append(res, err)
	}

	qState, qhkState, _ := qs.GetOK("state")
	if err := o.bindState(qState, qhkState, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindClientID binds and validates parameter ClientID from query.
func (o *GetOauth2AuthParams) bindClientID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("client_id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("client_id", "query", raw); err != nil {
		return err
	}
	o.ClientID = raw

	return nil
}

// bindCodeChallenge binds and validates parameter CodeChallenge from query.
func (o *GetOauth2AuthParams) bindCodeChallenge(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.CodeChallenge = &raw

	return nil
}

// bindCodeChallengeMethod binds and validates parameter CodeChallengeMethod from query.
func (o *GetOauth2AuthParams) bindCodeChallengeMethod(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.CodeChallengeMethod = &raw

	if err := o.validateCodeChallengeMethod(formats); err != nil {
		return err
	}

	return nil
}

// validateCodeChallengeMethod carries on validations for parameter CodeChallengeMethod
func (o *GetOauth2AuthParams) validateCodeChallengeMethod(formats strfmt.Registry) error {

	if err := validate.EnumCase("code_challenge_method", "query", *o.CodeChallengeMethod, []interface{}{"S256"}, true); err != nil {
		return err
	}

	return nil
}

// bindRedirectURI binds and validates parameter RedirectURI from query.
func (o *GetOauth2AuthParams) bindRedirectURI(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("redirect_uri", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("redirect_uri", "query", raw); err != nil {
		return err
	}
	o.RedirectURI = raw

	return nil
}

// bindResponseType binds and validates parameter ResponseType from query.
func (o *GetOauth2AuthParams) bindResponseType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("response_type", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("response_type", "query", raw); err != nil {
		return err
	}
	o.ResponseType = raw

	if err := o.validateResponseType(formats); err != nil {
		return err
	}

	return nil
}

// validateResponseType carries on validations for parameter ResponseType
func (o *GetOauth2AuthParams) validateResponseType(formats strfmt.Registry) error {

	if err := validate.EnumCase("response_type", "query", o.ResponseType, []interface{}{"code"}, true); err != nil {
		return err
	}

	return nil
}

// bindScope binds and validates parameter Scope from query.
func (o *GetOauth2AuthParams) bindScope(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetOauth2AuthParams()
		return nil
	}
	o.Scope = &raw

	return nil
}

// bindState binds and validates parameter State from query.
func (o *GetOauth2AuthParams) bindState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.State = &raw

	return nil
}
