// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Mindwell",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/account/email/{email}": {
      "get": {
        "tags": [
          "account"
        ],
        "summary": "check if email is used",
        "parameters": [
          {
            "maxLength": 500,
            "type": "string",
            "name": "email",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "check result",
            "schema": {
              "type": "object",
              "required": [
                "email",
                "isFree"
              ],
              "properties": {
                "email": {
                  "type": "string"
                },
                "isFree": {
                  "type": "boolean"
                }
              },
              "example": {
                "email": "mail@example.com",
                "isFree": true
              }
            }
          }
        }
      }
    },
    "/account/invites": {
      "get": {
        "tags": [
          "account"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "invite list",
            "schema": {
              "type": "object",
              "properties": {
                "invites": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/login": {
      "post": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "account"
        ],
        "parameters": [
          {
            "maxLength": 20,
            "minLength": 1,
            "type": "string",
            "name": "name",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 500,
            "minLength": 6,
            "type": "string",
            "name": "password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AuthProfile"
            }
          },
          "400": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/name/{name}": {
      "get": {
        "tags": [
          "account"
        ],
        "summary": "check if name is used",
        "parameters": [
          {
            "maxLength": 20,
            "minLength": 1,
            "type": "string",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "check result",
            "schema": {
              "type": "object",
              "required": [
                "name",
                "isFree"
              ],
              "properties": {
                "isFree": {
                  "type": "boolean"
                },
                "name": {
                  "type": "string"
                }
              },
              "example": {
                "isFree": false,
                "name": "example"
              }
            }
          }
        }
      }
    },
    "/account/password": {
      "post": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "account"
        ],
        "summary": "set new password",
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "maxLength": 100,
            "minLength": 6,
            "type": "string",
            "name": "old_password",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 100,
            "minLength": 6,
            "type": "string",
            "name": "new_password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "password has been set"
          },
          "403": {
            "description": "access denied or old password",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/recover": {
      "post": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "account"
        ],
        "parameters": [
          {
            "maxLength": 500,
            "type": "string",
            "name": "email",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Email not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/register": {
      "post": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "account"
        ],
        "summary": "register new account",
        "parameters": [
          {
            "maxLength": 20,
            "minLength": 1,
            "type": "string",
            "name": "name",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 500,
            "type": "string",
            "name": "email",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 100,
            "minLength": 6,
            "type": "string",
            "name": "password",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 100,
            "type": "string",
            "name": "invite",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 20,
            "minLength": 1,
            "type": "string",
            "name": "referrer",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "format": "full-date",
            "name": "birthday",
            "in": "formData"
          },
          {
            "enum": [
              "not set",
              "male",
              "female"
            ],
            "type": "string",
            "default": "not set",
            "name": "gender",
            "in": "formData"
          },
          {
            "maxLength": 50,
            "type": "string",
            "default": "",
            "name": "country",
            "in": "formData"
          },
          {
            "maxLength": 50,
            "type": "string",
            "default": "",
            "name": "city",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AuthProfile"
            }
          },
          "400": {
            "description": "email or name already exists",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/verification": {
      "post": {
        "tags": [
          "account"
        ],
        "summary": "request verification email",
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "email has been sent"
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/verification/{email}": {
      "get": {
        "tags": [
          "account"
        ],
        "summary": "verify account email",
        "parameters": [
          {
            "maxLength": 500,
            "type": "string",
            "name": "email",
            "in": "path",
            "required": true
          },
          {
            "maxLength": 64,
            "minLength": 64,
            "type": "string",
            "name": "code",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "verified"
          },
          "400": {
            "description": "code or email is not valid",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/comments/{id}": {
      "get": {
        "tags": [
          "comments"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "Comment data",
            "schema": {
              "$ref": "#/definitions/Comment"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Comment not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "comments"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "maxLength": 1000,
            "minLength": 1,
            "type": "string",
            "name": "content",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Comment data",
            "schema": {
              "$ref": "#/definitions/Comment"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Comment not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "comments"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Comment not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathId"
        }
      ]
    },
    "/comments/{id}/vote": {
      "get": {
        "tags": [
          "votes"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "vote status",
            "schema": {
              "$ref": "#/definitions/Rating"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathId"
        }
      ]
    },
    "/design": {
      "get": {
        "tags": [
          "design"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "Design of your tlog",
            "schema": {
              "$ref": "#/definitions/Design"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "design"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "maxLength": 10000,
            "type": "string",
            "default": "",
            "name": "css",
            "in": "formData"
          },
          {
            "pattern": "#[0-9a-fA-F]{6}",
            "type": "string",
            "default": "#ffffff",
            "name": "backgroundColor",
            "in": "formData"
          },
          {
            "pattern": "#[0-9a-fA-F]{6}",
            "type": "string",
            "default": "#000000",
            "name": "textColor",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "fontFamily",
            "in": "formData"
          },
          {
            "type": "integer",
            "name": "fontSize",
            "in": "formData"
          },
          {
            "enum": [
              "left",
              "right",
              "center",
              "justify"
            ],
            "type": "string",
            "name": "textAlignment",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Design of your tlog",
            "schema": {
              "$ref": "#/definitions/Design"
            }
          }
        }
      }
    },
    "/design/fonts": {
      "get": {
        "tags": [
          "design"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "List of available font families",
            "schema": {
              "type": "object",
              "properties": {
                "fonts": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/entries/anonymous": {
      "get": {
        "tags": [
          "entries"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          },
          {
            "$ref": "#/parameters/tag"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "entries"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "maxLength": 500,
            "type": "string",
            "default": "",
            "name": "title",
            "in": "formData"
          },
          {
            "maxLength": 30000,
            "minLength": 1,
            "type": "string",
            "name": "content",
            "in": "formData",
            "required": true
          },
          {
            "type": "boolean",
            "default": false,
            "name": "anonymous_comments",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "Entry data",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/entries/best": {
      "get": {
        "tags": [
          "entries"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          },
          {
            "$ref": "#/parameters/tag"
          },
          {
            "type": "integer",
            "name": "min_rating",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          }
        }
      }
    },
    "/entries/friends": {
      "get": {
        "tags": [
          "entries"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          },
          {
            "$ref": "#/parameters/tag"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          }
        }
      }
    },
    "/entries/live": {
      "get": {
        "tags": [
          "entries"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          },
          {
            "$ref": "#/parameters/tag"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          }
        }
      }
    },
    "/entries/{id}": {
      "get": {
        "tags": [
          "entries"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "Entry data",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "entries"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "maxLength": 500,
            "type": "string",
            "default": "",
            "name": "title",
            "in": "formData"
          },
          {
            "maxLength": 30000,
            "minLength": 1,
            "type": "string",
            "name": "content",
            "in": "formData",
            "required": true
          },
          {
            "enum": [
              "all",
              "followers",
              "some",
              "me",
              "anonymous"
            ],
            "type": "string",
            "name": "privacy",
            "in": "formData",
            "required": true
          },
          {
            "type": "array",
            "items": {
              "minimum": 1,
              "type": "integer",
              "format": "int64"
            },
            "name": "visibleFor",
            "in": "formData"
          },
          {
            "type": "boolean",
            "default": false,
            "name": "isVotable",
            "in": "formData"
          },
          {
            "type": "boolean",
            "default": false,
            "name": "anonymous_comments",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry data",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "entries"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathId"
        }
      ]
    },
    "/entries/{id}/comments": {
      "get": {
        "tags": [
          "comments"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          }
        ],
        "responses": {
          "200": {
            "description": "comments list",
            "schema": {
              "$ref": "#/definitions/CommentList"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "comments"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "maxLength": 1000,
            "minLength": 1,
            "type": "string",
            "name": "content",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Comment data",
            "schema": {
              "$ref": "#/definitions/Comment"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathId"
        }
      ]
    },
    "/entries/{id}/favorite": {
      "get": {
        "tags": [
          "favorites"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "favorite status",
            "schema": {
              "$ref": "#/definitions/FavoriteStatus"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "favorites"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "favorite status",
            "schema": {
              "$ref": "#/definitions/FavoriteStatus"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "favorites"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "favorite status",
            "schema": {
              "$ref": "#/definitions/FavoriteStatus"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathId"
        }
      ]
    },
    "/entries/{id}/vote": {
      "get": {
        "tags": [
          "votes"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "vote status",
            "schema": {
              "$ref": "#/definitions/Rating"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "votes"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "type": "boolean",
            "default": true,
            "name": "positive",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "vote status",
            "schema": {
              "$ref": "#/definitions/Rating"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "votes"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "vote status",
            "schema": {
              "$ref": "#/definitions/Rating"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathId"
        }
      ]
    },
    "/entries/{id}/watching": {
      "get": {
        "tags": [
          "watchings"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "watching status",
            "schema": {
              "$ref": "#/definitions/WatchingStatus"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "watchings"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "watching status",
            "schema": {
              "$ref": "#/definitions/WatchingStatus"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "watchings"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "watching status",
            "schema": {
              "$ref": "#/definitions/WatchingStatus"
            }
          },
          "404": {
            "description": "Entry not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathId"
        }
      ]
    },
    "/me": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "your data",
            "schema": {
              "$ref": "#/definitions/AuthProfile"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "maxLength": 20,
            "minLength": 1,
            "type": "string",
            "name": "showName",
            "in": "formData",
            "required": true
          },
          {
            "enum": [
              "male",
              "female",
              "not set"
            ],
            "type": "string",
            "default": "not set",
            "name": "gender",
            "in": "formData"
          },
          {
            "type": "boolean",
            "default": false,
            "name": "isDaylog",
            "in": "formData"
          },
          {
            "enum": [
              "all",
              "followers"
            ],
            "type": "string",
            "name": "privacy",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 500,
            "type": "string",
            "default": "",
            "name": "title",
            "in": "formData"
          },
          {
            "type": "string",
            "format": "full-date",
            "default": "",
            "name": "birthday",
            "in": "formData"
          },
          {
            "maxLength": 50,
            "type": "string",
            "default": "",
            "name": "country",
            "in": "formData"
          },
          {
            "maxLength": 50,
            "type": "string",
            "default": "",
            "name": "city",
            "in": "formData"
          },
          {
            "type": "boolean",
            "default": false,
            "name": "showInTops",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "your data",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/avatar": {
      "put": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "Avatar",
            "schema": {
              "$ref": "#/definitions/Avatar"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/cover": {
      "put": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "Cover",
            "schema": {
              "$ref": "#/definitions/Cover"
            }
          },
          "400": {
            "description": "bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/favorites": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/followers": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/skip"
          }
        ],
        "responses": {
          "200": {
            "description": "User list",
            "schema": {
              "$ref": "#/definitions/FriendList"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/followings": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/skip"
          }
        ],
        "responses": {
          "200": {
            "description": "User list",
            "schema": {
              "$ref": "#/definitions/FriendList"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/ignored": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/skip"
          }
        ],
        "responses": {
          "200": {
            "description": "User list",
            "schema": {
              "$ref": "#/definitions/FriendList"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/invited": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/skip"
          }
        ],
        "responses": {
          "200": {
            "description": "User list",
            "schema": {
              "$ref": "#/definitions/FriendList"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/online": {
      "put": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/me/requested": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/skip"
          }
        ],
        "responses": {
          "200": {
            "description": "User list",
            "schema": {
              "$ref": "#/definitions/FriendList"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/tlog": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          },
          {
            "$ref": "#/parameters/tag"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data",
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "maxLength": 500,
            "type": "string",
            "default": "",
            "name": "title",
            "in": "formData"
          },
          {
            "maxLength": 30000,
            "minLength": 1,
            "type": "string",
            "name": "content",
            "in": "formData",
            "required": true
          },
          {
            "enum": [
              "all",
              "followers",
              "some",
              "me"
            ],
            "type": "string",
            "name": "privacy",
            "in": "formData",
            "required": true
          },
          {
            "type": "array",
            "items": {
              "minimum": 1,
              "type": "integer",
              "format": "int64"
            },
            "name": "visibleFor",
            "in": "formData"
          },
          {
            "type": "boolean",
            "default": false,
            "name": "isVotable",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "Entry data",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/me/watching": {
      "get": {
        "tags": [
          "me"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/relations/from/{name}": {
      "get": {
        "tags": [
          "relations"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "the user relationship with you",
            "schema": {
              "$ref": "#/definitions/Relationship"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "relations"
        ],
        "summary": "permit the user to follow you",
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "the user relationship with you",
            "schema": {
              "$ref": "#/definitions/Relationship"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "relations"
        ],
        "summary": "cancel following request or unsubscribe the user",
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "the user relationship with you",
            "schema": {
              "$ref": "#/definitions/Relationship"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathName"
        }
      ]
    },
    "/relations/to/{name}": {
      "get": {
        "tags": [
          "relations"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "your relationship with the user",
            "schema": {
              "$ref": "#/definitions/Relationship"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "relations"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "enum": [
              "followed",
              "ignored"
            ],
            "type": "string",
            "name": "r",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "your relationship with the user",
            "schema": {
              "$ref": "#/definitions/Relationship"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "relations"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "your relationship with the user",
            "schema": {
              "$ref": "#/definitions/Relationship"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathName"
        }
      ]
    },
    "/users/{name}": {
      "get": {
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "responses": {
          "200": {
            "description": "User data",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathName"
        }
      ]
    },
    "/users/{name}/favorites": {
      "get": {
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathName"
        }
      ]
    },
    "/users/{name}/followers": {
      "get": {
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/skip"
          }
        ],
        "responses": {
          "200": {
            "description": "User list",
            "schema": {
              "$ref": "#/definitions/FriendList"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathName"
        }
      ]
    },
    "/users/{name}/followings": {
      "get": {
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/skip"
          }
        ],
        "responses": {
          "200": {
            "description": "User list",
            "schema": {
              "$ref": "#/definitions/FriendList"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathName"
        }
      ]
    },
    "/users/{name}/invited": {
      "get": {
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/skip"
          }
        ],
        "responses": {
          "200": {
            "description": "User list",
            "schema": {
              "$ref": "#/definitions/FriendList"
            }
          },
          "403": {
            "description": "access denied",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathName"
        }
      ]
    },
    "/users/{name}/tlog": {
      "get": {
        "tags": [
          "users"
        ],
        "security": [
          {
            "ApiKeyHeader": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/after"
          },
          {
            "$ref": "#/parameters/before"
          },
          {
            "$ref": "#/parameters/tag"
          },
          {
            "$ref": "#/parameters/sort"
          }
        ],
        "responses": {
          "200": {
            "description": "Entry list",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/parameters/pathName"
        }
      ]
    }
  },
  "definitions": {
    "AuthProfile": {
      "allOf": [
        {
          "$ref": "#/definitions/Profile"
        },
        {
          "type": "object",
          "properties": {
            "account": {
              "type": "object",
              "properties": {
                "apiKey": {
                  "type": "string"
                },
                "email": {
                  "type": "string"
                },
                "validThru": {
                  "type": "number",
                  "format": "double"
                },
                "verified": {
                  "type": "boolean"
                }
              }
            },
            "birthday": {
              "type": "string",
              "format": "full-date"
            },
            "showInTops": {
              "type": "boolean"
            }
          },
          "example": {
            "account": {
              "apiKey": "blah-blah-blah",
              "email": "mail@example.com",
              "validThru": "1985-04-12T23:20:50.52Z",
              "verified": true
            }
          }
        }
      ]
    },
    "Avatar": {
      "type": "object",
      "properties": {
        "x124": {
          "type": "string"
        },
        "x42": {
          "type": "string"
        },
        "x92": {
          "type": "string"
        }
      }
    },
    "Color": {
      "description": "color in rgb",
      "type": "string",
      "pattern": "#[0-9a-fA-F]{6}",
      "example": "#373737"
    },
    "Comment": {
      "type": "object",
      "properties": {
        "author": {
          "$ref": "#/definitions/User"
        },
        "content": {
          "type": "string",
          "minLength": 1
        },
        "createdAt": {
          "type": "number",
          "format": "double"
        },
        "entryId": {
          "type": "integer",
          "format": "int64",
          "minimum": 1
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "minimum": 1
        },
        "rating": {
          "type": "integer"
        },
        "vote": {
          "type": "string",
          "enum": [
            "not",
            "pos",
            "neg",
            "ban"
          ]
        }
      },
      "example": {
        "content": "\u003cp\u003esome text with \u003cb\u003ehtml\u003c/b\u003e tags\u003c/p\u003e",
        "createdAt": "1985-04-12T23:20:50.52Z",
        "entryId": 152,
        "id": 999
      }
    },
    "CommentList": {
      "type": "object",
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Comment"
          }
        },
        "hasAfter": {
          "type": "boolean"
        },
        "hasBefore": {
          "type": "boolean"
        },
        "nextAfter": {
          "type": "string"
        },
        "nextBefore": {
          "type": "string"
        }
      }
    },
    "Cover": {
      "type": "object",
      "properties": {
        "id": {
          "description": "user id",
          "type": "integer",
          "format": "int64",
          "minimum": 1
        },
        "x1920": {
          "type": "string"
        },
        "x318": {
          "type": "string"
        }
      }
    },
    "Design": {
      "type": "object",
      "properties": {
        "backgroundColor": {
          "$ref": "#/definitions/Color"
        },
        "css": {
          "type": "string"
        },
        "fontFamily": {
          "type": "string"
        },
        "fontSize": {
          "type": "integer"
        },
        "textAlignment": {
          "type": "string",
          "enum": [
            "left",
            "right",
            "center",
            "justify"
          ]
        },
        "textColor": {
          "$ref": "#/definitions/Color"
        }
      }
    },
    "Entry": {
      "type": "object",
      "properties": {
        "author": {
          "$ref": "#/definitions/User"
        },
        "commentCount": {
          "type": "integer"
        },
        "comments": {
          "$ref": "#/definitions/CommentList"
        },
        "content": {
          "type": "string"
        },
        "createdAt": {
          "type": "number",
          "format": "double"
        },
        "cutContent": {
          "type": "string"
        },
        "cutTitle": {
          "type": "string"
        },
        "editContent": {
          "type": "string"
        },
        "hasCut": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "minimum": 1
        },
        "isFavorited": {
          "type": "boolean"
        },
        "isWatching": {
          "type": "boolean"
        },
        "privacy": {
          "type": "string",
          "enum": [
            "all",
            "some",
            "me",
            "anonymous"
          ]
        },
        "rating": {
          "$ref": "#/definitions/Rating"
        },
        "title": {
          "type": "string"
        },
        "visibleFor": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/User"
          }
        },
        "wordCount": {
          "type": "integer"
        }
      },
      "example": {
        "commentCount": 0,
        "content": "\u003cp\u003esome text with \u003cb\u003ehtml\u003c/b\u003e tags\u003c/p\u003e",
        "createdAt": "1985-04-12T23:20:50.52Z",
        "id": 152,
        "isVotable": true,
        "privacy": "all",
        "rating": -3,
        "title": "example title",
        "wordCount": 5
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      },
      "example": {
        "message": "Access denied"
      }
    },
    "FavoriteStatus": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "minimum": 1
        },
        "isFavorited": {
          "type": "boolean"
        }
      }
    },
    "Feed": {
      "type": "object",
      "properties": {
        "entries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Entry"
          }
        },
        "hasAfter": {
          "type": "boolean"
        },
        "hasBefore": {
          "type": "boolean"
        },
        "nextAfter": {
          "type": "string"
        },
        "nextBefore": {
          "type": "string"
        }
      }
    },
    "Friend": {
      "allOf": [
        {
          "$ref": "#/definitions/User"
        },
        {
          "type": "object",
          "properties": {
            "counts": {
              "type": "object",
              "properties": {
                "comments": {
                  "type": "integer"
                },
                "entries": {
                  "type": "integer"
                },
                "favorites": {
                  "type": "integer"
                },
                "followers": {
                  "type": "integer"
                },
                "followings": {
                  "type": "integer"
                },
                "ignored": {
                  "type": "integer"
                },
                "invited": {
                  "type": "integer"
                },
                "tags": {
                  "type": "integer"
                }
              }
            },
            "cover": {
              "$ref": "#/definitions/Cover"
            },
            "karma": {
              "type": "number",
              "format": "float"
            },
            "lastSeenAt": {
              "type": "number",
              "format": "double"
            },
            "title": {
              "type": "string",
              "maxLength": 260
            }
          }
        }
      ]
    },
    "FriendList": {
      "type": "object",
      "required": [
        "users"
      ],
      "properties": {
        "relation": {
          "type": "string",
          "enum": [
            "followers",
            "followings",
            "requested",
            "ignored",
            "invited"
          ]
        },
        "subject": {
          "$ref": "#/definitions/User"
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Friend"
          }
        }
      }
    },
    "Profile": {
      "allOf": [
        {
          "$ref": "#/definitions/Friend"
        },
        {
          "type": "object",
          "properties": {
            "ageLowerBound": {
              "type": "integer"
            },
            "ageUpperBound": {
              "type": "integer"
            },
            "city": {
              "type": "string",
              "maxLength": 50
            },
            "country": {
              "type": "string",
              "maxLength": 50
            },
            "createdAt": {
              "type": "number",
              "format": "double"
            },
            "design": {
              "$ref": "#/definitions/Design"
            },
            "gender": {
              "type": "string",
              "enum": [
                "male",
                "female",
                "not set"
              ]
            },
            "invitedBy": {
              "$ref": "#/definitions/User"
            },
            "isDaylog": {
              "type": "boolean"
            },
            "privacy": {
              "type": "string",
              "enum": [
                "all",
                "followers"
              ]
            },
            "relations": {
              "type": "object",
              "properties": {
                "fromMe": {
                  "type": "string",
                  "enum": [
                    "followed",
                    "requested",
                    "ignored",
                    "none"
                  ]
                },
                "toMe": {
                  "type": "string",
                  "enum": [
                    "followed",
                    "requested",
                    "ignored",
                    "none"
                  ]
                }
              }
            }
          },
          "example": {
            "city": "Казань",
            "country": "Россия",
            "counts": {
              "comments": 22,
              "entries": 13,
              "favorites": 1,
              "followers": 15,
              "followings": 4,
              "ignored": 0,
              "invited": 0,
              "tags": 0
            },
            "createdAt": "1985-04-12T23:20:50.52Z",
            "gender": "male",
            "isDaylog": false,
            "karma": 100,
            "lastSeenAt": "1985-04-12T23:20:50.52Z",
            "privacy": "registered",
            "relations": {
              "fromMe": "followed",
              "toMe": "none"
            },
            "title": "some tlog title"
          }
        }
      ]
    },
    "Rating": {
      "type": "object",
      "properties": {
        "downCount": {
          "type": "integer"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "minimum": 1
        },
        "isVotable": {
          "type": "boolean"
        },
        "rating": {
          "type": "number",
          "format": "float"
        },
        "upCount": {
          "type": "integer"
        },
        "vote": {
          "type": "string",
          "enum": [
            "not",
            "pos",
            "neg",
            "ban"
          ]
        }
      }
    },
    "Relationship": {
      "type": "object",
      "properties": {
        "from": {
          "type": "string"
        },
        "relation": {
          "type": "string",
          "enum": [
            "followed",
            "requested",
            "ignored",
            "none"
          ]
        },
        "to": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "avatar": {
          "$ref": "#/definitions/Avatar"
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "minimum": 1
        },
        "isOnline": {
          "type": "boolean"
        },
        "name": {
          "type": "string",
          "maxLength": 20,
          "minLength": 1
        },
        "showName": {
          "type": "string",
          "maxLength": 20,
          "minLength": 1
        }
      },
      "example": {
        "id": 1,
        "isOnline": false,
        "name": "binque",
        "showName": "Бинк"
      }
    },
    "UserID": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string",
          "maxLength": 20,
          "minLength": 1
        }
      }
    },
    "WatchingStatus": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "minimum": 1
        },
        "isWatching": {
          "type": "boolean"
        }
      }
    }
  },
  "parameters": {
    "after": {
      "type": "string",
      "default": "",
      "name": "after",
      "in": "query"
    },
    "before": {
      "type": "string",
      "default": "",
      "name": "before",
      "in": "query"
    },
    "limit": {
      "maximum": 100,
      "minimum": 1,
      "type": "integer",
      "default": 50,
      "name": "limit",
      "in": "query"
    },
    "pathId": {
      "minimum": 1,
      "type": "integer",
      "format": "int64",
      "name": "id",
      "in": "path",
      "required": true
    },
    "pathName": {
      "maxLength": 20,
      "minLength": 1,
      "type": "string",
      "name": "name",
      "in": "path",
      "required": true
    },
    "skip": {
      "type": "integer",
      "default": 0,
      "name": "skip",
      "in": "query"
    },
    "sort": {
      "enum": [
        "new",
        "old",
        "best"
      ],
      "type": "string",
      "default": "new",
      "name": "sort",
      "in": "query"
    },
    "tag": {
      "maxLength": 50,
      "type": "string",
      "name": "tag",
      "in": "query"
    }
  },
  "securityDefinitions": {
    "ApiKeyHeader": {
      "type": "apiKey",
      "name": "X-User-Key",
      "in": "header"
    }
  }
}`))
}
