// Code generated by go-swagger; DO NOT EDIT.

package oauth2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/mindwell-server/models"
)

// GetOauth2AuthOKCode is the HTTP code returned for type GetOauth2AuthOK
const GetOauth2AuthOKCode int = 200

/*GetOauth2AuthOK auth code

swagger:response getOauth2AuthOK
*/
type GetOauth2AuthOK struct {

	/*
	  In: Body
	*/
	Payload *GetOauth2AuthOKBody `json:"body,omitempty"`
}

// NewGetOauth2AuthOK creates GetOauth2AuthOK with default headers values
func NewGetOauth2AuthOK() *GetOauth2AuthOK {

	return &GetOauth2AuthOK{}
}

// WithPayload adds the payload to the get oauth2 auth o k response
func (o *GetOauth2AuthOK) WithPayload(payload *GetOauth2AuthOKBody) *GetOauth2AuthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get oauth2 auth o k response
func (o *GetOauth2AuthOK) SetPayload(payload *GetOauth2AuthOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOauth2AuthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOauth2AuthBadRequestCode is the HTTP code returned for type GetOauth2AuthBadRequest
const GetOauth2AuthBadRequestCode int = 400

/*GetOauth2AuthBadRequest some error happened

swagger:response getOauth2AuthBadRequest
*/
type GetOauth2AuthBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.OAuth2Error `json:"body,omitempty"`
}

// NewGetOauth2AuthBadRequest creates GetOauth2AuthBadRequest with default headers values
func NewGetOauth2AuthBadRequest() *GetOauth2AuthBadRequest {

	return &GetOauth2AuthBadRequest{}
}

// WithPayload adds the payload to the get oauth2 auth bad request response
func (o *GetOauth2AuthBadRequest) WithPayload(payload *models.OAuth2Error) *GetOauth2AuthBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get oauth2 auth bad request response
func (o *GetOauth2AuthBadRequest) SetPayload(payload *models.OAuth2Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOauth2AuthBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOauth2AuthUnauthorizedCode is the HTTP code returned for type GetOauth2AuthUnauthorized
const GetOauth2AuthUnauthorizedCode int = 401

/*GetOauth2AuthUnauthorized invalid client

swagger:response getOauth2AuthUnauthorized
*/
type GetOauth2AuthUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.OAuth2Error `json:"body,omitempty"`
}

// NewGetOauth2AuthUnauthorized creates GetOauth2AuthUnauthorized with default headers values
func NewGetOauth2AuthUnauthorized() *GetOauth2AuthUnauthorized {

	return &GetOauth2AuthUnauthorized{}
}

// WithPayload adds the payload to the get oauth2 auth unauthorized response
func (o *GetOauth2AuthUnauthorized) WithPayload(payload *models.OAuth2Error) *GetOauth2AuthUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get oauth2 auth unauthorized response
func (o *GetOauth2AuthUnauthorized) SetPayload(payload *models.OAuth2Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOauth2AuthUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
