// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/yummy-server/models"
)

// GetUsersMeFollowersOKCode is the HTTP code returned for type GetUsersMeFollowersOK
const GetUsersMeFollowersOKCode int = 200

/*GetUsersMeFollowersOK User list

swagger:response getUsersMeFollowersOK
*/
type GetUsersMeFollowersOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserList `json:"body,omitempty"`
}

// NewGetUsersMeFollowersOK creates GetUsersMeFollowersOK with default headers values
func NewGetUsersMeFollowersOK() *GetUsersMeFollowersOK {
	return &GetUsersMeFollowersOK{}
}

// WithPayload adds the payload to the get users me followers o k response
func (o *GetUsersMeFollowersOK) WithPayload(payload *models.UserList) *GetUsersMeFollowersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users me followers o k response
func (o *GetUsersMeFollowersOK) SetPayload(payload *models.UserList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersMeFollowersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersMeFollowersForbiddenCode is the HTTP code returned for type GetUsersMeFollowersForbidden
const GetUsersMeFollowersForbiddenCode int = 403

/*GetUsersMeFollowersForbidden access denied

swagger:response getUsersMeFollowersForbidden
*/
type GetUsersMeFollowersForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUsersMeFollowersForbidden creates GetUsersMeFollowersForbidden with default headers values
func NewGetUsersMeFollowersForbidden() *GetUsersMeFollowersForbidden {
	return &GetUsersMeFollowersForbidden{}
}

// WithPayload adds the payload to the get users me followers forbidden response
func (o *GetUsersMeFollowersForbidden) WithPayload(payload *models.Error) *GetUsersMeFollowersForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users me followers forbidden response
func (o *GetUsersMeFollowersForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersMeFollowersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
