// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	models "github.com/sevings/mindwell-server/models"
)

// GetMeFollowingsOKCode is the HTTP code returned for type GetMeFollowingsOK
const GetMeFollowingsOKCode int = 200

/*GetMeFollowingsOK User list

swagger:response getMeFollowingsOK
*/
type GetMeFollowingsOK struct {

	/*
	  In: Body
	*/
	Payload *models.FriendList `json:"body,omitempty"`
}

// NewGetMeFollowingsOK creates GetMeFollowingsOK with default headers values
func NewGetMeFollowingsOK() *GetMeFollowingsOK {

	return &GetMeFollowingsOK{}
}

// WithPayload adds the payload to the get me followings o k response
func (o *GetMeFollowingsOK) WithPayload(payload *models.FriendList) *GetMeFollowingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get me followings o k response
func (o *GetMeFollowingsOK) SetPayload(payload *models.FriendList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeFollowingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
