// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/sevings/yummy-server/models"
)

// GetUsersMeHandlerFunc turns a function with the right signature into a get users me handler
type GetUsersMeHandlerFunc func(GetUsersMeParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUsersMeHandlerFunc) Handle(params GetUsersMeParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// GetUsersMeHandler interface for that can handle valid get users me params
type GetUsersMeHandler interface {
	Handle(GetUsersMeParams, *models.UserID) middleware.Responder
}

// NewGetUsersMe creates a new http.Handler for the get users me operation
func NewGetUsersMe(ctx *middleware.Context, handler GetUsersMeHandler) *GetUsersMe {
	return &GetUsersMe{Context: ctx, Handler: handler}
}

/*GetUsersMe swagger:route GET /users/me me getUsersMe

GetUsersMe get users me API

*/
type GetUsersMe struct {
	Context *middleware.Context
	Handler GetUsersMeHandler
}

func (o *GetUsersMe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUsersMeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
