// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/sevings/mindwell-server/models"
)

// GetMeFavoritesHandlerFunc turns a function with the right signature into a get me favorites handler
type GetMeFavoritesHandlerFunc func(GetMeFavoritesParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMeFavoritesHandlerFunc) Handle(params GetMeFavoritesParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// GetMeFavoritesHandler interface for that can handle valid get me favorites params
type GetMeFavoritesHandler interface {
	Handle(GetMeFavoritesParams, *models.UserID) middleware.Responder
}

// NewGetMeFavorites creates a new http.Handler for the get me favorites operation
func NewGetMeFavorites(ctx *middleware.Context, handler GetMeFavoritesHandler) *GetMeFavorites {
	return &GetMeFavorites{Context: ctx, Handler: handler}
}

/* GetMeFavorites swagger:route GET /me/favorites me getMeFavorites

GetMeFavorites get me favorites API

*/
type GetMeFavorites struct {
	Context *middleware.Context
	Handler GetMeFavoritesHandler
}

func (o *GetMeFavorites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMeFavoritesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
