// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/mindwell-server/models"
)

// GetMeHiddenOKCode is the HTTP code returned for type GetMeHiddenOK
const GetMeHiddenOKCode int = 200

/*GetMeHiddenOK User list

swagger:response getMeHiddenOK
*/
type GetMeHiddenOK struct {

	/*
	  In: Body
	*/
	Payload *models.FriendList `json:"body,omitempty"`
}

// NewGetMeHiddenOK creates GetMeHiddenOK with default headers values
func NewGetMeHiddenOK() *GetMeHiddenOK {

	return &GetMeHiddenOK{}
}

// WithPayload adds the payload to the get me hidden o k response
func (o *GetMeHiddenOK) WithPayload(payload *models.FriendList) *GetMeHiddenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get me hidden o k response
func (o *GetMeHiddenOK) SetPayload(payload *models.FriendList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeHiddenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
