// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/sevings/mindwell-server/models"
)

// PostMeTlogHandlerFunc turns a function with the right signature into a post me tlog handler
type PostMeTlogHandlerFunc func(PostMeTlogParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMeTlogHandlerFunc) Handle(params PostMeTlogParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// PostMeTlogHandler interface for that can handle valid post me tlog params
type PostMeTlogHandler interface {
	Handle(PostMeTlogParams, *models.UserID) middleware.Responder
}

// NewPostMeTlog creates a new http.Handler for the post me tlog operation
func NewPostMeTlog(ctx *middleware.Context, handler PostMeTlogHandler) *PostMeTlog {
	return &PostMeTlog{Context: ctx, Handler: handler}
}

/* PostMeTlog swagger:route POST /me/tlog me postMeTlog

PostMeTlog post me tlog API

*/
type PostMeTlog struct {
	Context *middleware.Context
	Handler PostMeTlogHandler
}

func (o *PostMeTlog) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMeTlogParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
