// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutMeOnlineOKCode is the HTTP code returned for type PutMeOnlineOK
const PutMeOnlineOKCode int = 200

/*PutMeOnlineOK OK

swagger:response putMeOnlineOK
*/
type PutMeOnlineOK struct {
}

// NewPutMeOnlineOK creates PutMeOnlineOK with default headers values
func NewPutMeOnlineOK() *PutMeOnlineOK {

	return &PutMeOnlineOK{}
}

// WriteResponse to the client
func (o *PutMeOnlineOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
