// Code generated by go-swagger; DO NOT EDIT.

package adm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/mindwell-server/models"
)

// GetAdmStatOKCode is the HTTP code returned for type GetAdmStatOK
const GetAdmStatOKCode int = 200

/*GetAdmStatOK ADM stats

swagger:response getAdmStatOK
*/
type GetAdmStatOK struct {

	/*
	  In: Body
	*/
	Payload *GetAdmStatOKBody `json:"body,omitempty"`
}

// NewGetAdmStatOK creates GetAdmStatOK with default headers values
func NewGetAdmStatOK() *GetAdmStatOK {

	return &GetAdmStatOK{}
}

// WithPayload adds the payload to the get adm stat o k response
func (o *GetAdmStatOK) WithPayload(payload *GetAdmStatOKBody) *GetAdmStatOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get adm stat o k response
func (o *GetAdmStatOK) SetPayload(payload *GetAdmStatOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdmStatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAdmStatGoneCode is the HTTP code returned for type GetAdmStatGone
const GetAdmStatGoneCode int = 410

/*GetAdmStatGone adm finished

swagger:response getAdmStatGone
*/
type GetAdmStatGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAdmStatGone creates GetAdmStatGone with default headers values
func NewGetAdmStatGone() *GetAdmStatGone {

	return &GetAdmStatGone{}
}

// WithPayload adds the payload to the get adm stat gone response
func (o *GetAdmStatGone) WithPayload(payload *models.Error) *GetAdmStatGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get adm stat gone response
func (o *GetAdmStatGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdmStatGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
