// Code generated by go-swagger; DO NOT EDIT.

package adm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/sevings/mindwell-server/models"
)

// GetAdmGrandfatherHandlerFunc turns a function with the right signature into a get adm grandfather handler
type GetAdmGrandfatherHandlerFunc func(GetAdmGrandfatherParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAdmGrandfatherHandlerFunc) Handle(params GetAdmGrandfatherParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// GetAdmGrandfatherHandler interface for that can handle valid get adm grandfather params
type GetAdmGrandfatherHandler interface {
	Handle(GetAdmGrandfatherParams, *models.UserID) middleware.Responder
}

// NewGetAdmGrandfather creates a new http.Handler for the get adm grandfather operation
func NewGetAdmGrandfather(ctx *middleware.Context, handler GetAdmGrandfatherHandler) *GetAdmGrandfather {
	return &GetAdmGrandfather{Context: ctx, Handler: handler}
}

/*GetAdmGrandfather swagger:route GET /adm/grandfather adm getAdmGrandfather

GetAdmGrandfather get adm grandfather API

*/
type GetAdmGrandfather struct {
	Context *middleware.Context
	Handler GetAdmGrandfatherHandler
}

func (o *GetAdmGrandfather) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAdmGrandfatherParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAdmGrandfatherOKBody get adm grandfather o k body
// swagger:model GetAdmGrandfatherOKBody
type GetAdmGrandfatherOKBody struct {

	// address
	Address string `json:"address,omitempty"`

	// comment
	Comment string `json:"comment,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// fullname
	Fullname string `json:"fullname,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// postcode
	Postcode string `json:"postcode,omitempty"`
}

// Validate validates this get adm grandfather o k body
func (o *GetAdmGrandfatherOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAdmGrandfatherOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAdmGrandfatherOKBody) UnmarshalBinary(b []byte) error {
	var res GetAdmGrandfatherOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
