// Code generated by go-swagger; DO NOT EDIT.

package adm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAdmGrandsonParams creates a new PostAdmGrandsonParams object
// with the default values initialized.
func NewPostAdmGrandsonParams() PostAdmGrandsonParams {

	var (
		// initialize parameters with default values

		anonymousDefault = bool(false)
	)

	return PostAdmGrandsonParams{
		Anonymous: &anonymousDefault,
	}
}

// PostAdmGrandsonParams contains all the bound params for the post adm grandson operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostAdmGrandson
type PostAdmGrandsonParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: formData
	*/
	Address string
	/*
	  In: formData
	  Default: false
	*/
	Anonymous *bool
	/*
	  Required: true
	  In: formData
	*/
	Country string
	/*
	  Required: true
	  In: formData
	*/
	Name string
	/*
	  Required: true
	  In: formData
	*/
	Postcode string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostAdmGrandsonParams() beforehand.
func (o *PostAdmGrandsonParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}
	fds := runtime.Values(r.Form)

	fdAddress, fdhkAddress, _ := fds.GetOK("address")
	if err := o.bindAddress(fdAddress, fdhkAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	fdAnonymous, fdhkAnonymous, _ := fds.GetOK("anonymous")
	if err := o.bindAnonymous(fdAnonymous, fdhkAnonymous, route.Formats); err != nil {
		res = append(res, err)
	}

	fdCountry, fdhkCountry, _ := fds.GetOK("country")
	if err := o.bindCountry(fdCountry, fdhkCountry, route.Formats); err != nil {
		res = append(res, err)
	}

	fdName, fdhkName, _ := fds.GetOK("name")
	if err := o.bindName(fdName, fdhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	fdPostcode, fdhkPostcode, _ := fds.GetOK("postcode")
	if err := o.bindPostcode(fdPostcode, fdhkPostcode, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAddress binds and validates parameter Address from formData.
func (o *PostAdmGrandsonParams) bindAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("address", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("address", "formData", raw); err != nil {
		return err
	}

	o.Address = raw

	return nil
}

// bindAnonymous binds and validates parameter Anonymous from formData.
func (o *PostAdmGrandsonParams) bindAnonymous(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewPostAdmGrandsonParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("anonymous", "formData", "bool", raw)
	}
	o.Anonymous = &value

	return nil
}

// bindCountry binds and validates parameter Country from formData.
func (o *PostAdmGrandsonParams) bindCountry(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("country", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("country", "formData", raw); err != nil {
		return err
	}

	o.Country = raw

	return nil
}

// bindName binds and validates parameter Name from formData.
func (o *PostAdmGrandsonParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("name", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("name", "formData", raw); err != nil {
		return err
	}

	o.Name = raw

	return nil
}

// bindPostcode binds and validates parameter Postcode from formData.
func (o *PostAdmGrandsonParams) bindPostcode(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("postcode", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("postcode", "formData", raw); err != nil {
		return err
	}

	o.Postcode = raw

	return nil
}
