// Code generated by go-swagger; DO NOT EDIT.

package adm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/sevings/mindwell-server/models"
)

// PostAdmGrandsonStatusHandlerFunc turns a function with the right signature into a post adm grandson status handler
type PostAdmGrandsonStatusHandlerFunc func(PostAdmGrandsonStatusParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAdmGrandsonStatusHandlerFunc) Handle(params PostAdmGrandsonStatusParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// PostAdmGrandsonStatusHandler interface for that can handle valid post adm grandson status params
type PostAdmGrandsonStatusHandler interface {
	Handle(PostAdmGrandsonStatusParams, *models.UserID) middleware.Responder
}

// NewPostAdmGrandsonStatus creates a new http.Handler for the post adm grandson status operation
func NewPostAdmGrandsonStatus(ctx *middleware.Context, handler PostAdmGrandsonStatusHandler) *PostAdmGrandsonStatus {
	return &PostAdmGrandsonStatus{Context: ctx, Handler: handler}
}

/*PostAdmGrandsonStatus swagger:route POST /adm/grandson/status adm postAdmGrandsonStatus

PostAdmGrandsonStatus post adm grandson status API

*/
type PostAdmGrandsonStatus struct {
	Context *middleware.Context
	Handler PostAdmGrandsonStatusHandler
}

func (o *PostAdmGrandsonStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostAdmGrandsonStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
