// Code generated by go-swagger; DO NOT EDIT.

package favorites

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/sevings/mindwell-server/models"
)

// GetEntriesIDFavoriteHandlerFunc turns a function with the right signature into a get entries ID favorite handler
type GetEntriesIDFavoriteHandlerFunc func(GetEntriesIDFavoriteParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEntriesIDFavoriteHandlerFunc) Handle(params GetEntriesIDFavoriteParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// GetEntriesIDFavoriteHandler interface for that can handle valid get entries ID favorite params
type GetEntriesIDFavoriteHandler interface {
	Handle(GetEntriesIDFavoriteParams, *models.UserID) middleware.Responder
}

// NewGetEntriesIDFavorite creates a new http.Handler for the get entries ID favorite operation
func NewGetEntriesIDFavorite(ctx *middleware.Context, handler GetEntriesIDFavoriteHandler) *GetEntriesIDFavorite {
	return &GetEntriesIDFavorite{Context: ctx, Handler: handler}
}

/* GetEntriesIDFavorite swagger:route GET /entries/{id}/favorite favorites getEntriesIdFavorite

GetEntriesIDFavorite get entries ID favorite API

*/
type GetEntriesIDFavorite struct {
	Context *middleware.Context
	Handler GetEntriesIDFavoriteHandler
}

func (o *GetEntriesIDFavorite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEntriesIDFavoriteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
