// Code generated by go-swagger; DO NOT EDIT.

package chats

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sevings/mindwell-server/models"
)

// GetChatsOKCode is the HTTP code returned for type GetChatsOK
const GetChatsOKCode int = 200

/*GetChatsOK Chat list

swagger:response getChatsOK
*/
type GetChatsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ChatList `json:"body,omitempty"`
}

// NewGetChatsOK creates GetChatsOK with default headers values
func NewGetChatsOK() *GetChatsOK {

	return &GetChatsOK{}
}

// WithPayload adds the payload to the get chats o k response
func (o *GetChatsOK) WithPayload(payload *models.ChatList) *GetChatsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get chats o k response
func (o *GetChatsOK) SetPayload(payload *models.ChatList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChatsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
