// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	models "github.com/sevings/mindwell-server/models"
)

// DeleteCommentsIDHandlerFunc turns a function with the right signature into a delete comments ID handler
type DeleteCommentsIDHandlerFunc func(DeleteCommentsIDParams, *models.UserID) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCommentsIDHandlerFunc) Handle(params DeleteCommentsIDParams, principal *models.UserID) middleware.Responder {
	return fn(params, principal)
}

// DeleteCommentsIDHandler interface for that can handle valid delete comments ID params
type DeleteCommentsIDHandler interface {
	Handle(DeleteCommentsIDParams, *models.UserID) middleware.Responder
}

// NewDeleteCommentsID creates a new http.Handler for the delete comments ID operation
func NewDeleteCommentsID(ctx *middleware.Context, handler DeleteCommentsIDHandler) *DeleteCommentsID {
	return &DeleteCommentsID{Context: ctx, Handler: handler}
}

/*DeleteCommentsID swagger:route DELETE /comments/{id} comments deleteCommentsId

DeleteCommentsID delete comments ID API

*/
type DeleteCommentsID struct {
	Context *middleware.Context
	Handler DeleteCommentsIDHandler
}

func (o *DeleteCommentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCommentsIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.UserID
	if uprinc != nil {
		principal = uprinc.(*models.UserID) // this is really a models.UserID, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
