// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	models "github.com/sevings/mindwell-server/models"
)

// GetCommentsIDOKCode is the HTTP code returned for type GetCommentsIDOK
const GetCommentsIDOKCode int = 200

/*GetCommentsIDOK Comment data

swagger:response getCommentsIdOK
*/
type GetCommentsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Comment `json:"body,omitempty"`
}

// NewGetCommentsIDOK creates GetCommentsIDOK with default headers values
func NewGetCommentsIDOK() *GetCommentsIDOK {

	return &GetCommentsIDOK{}
}

// WithPayload adds the payload to the get comments Id o k response
func (o *GetCommentsIDOK) WithPayload(payload *models.Comment) *GetCommentsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get comments Id o k response
func (o *GetCommentsIDOK) SetPayload(payload *models.Comment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommentsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCommentsIDForbiddenCode is the HTTP code returned for type GetCommentsIDForbidden
const GetCommentsIDForbiddenCode int = 403

/*GetCommentsIDForbidden access denied

swagger:response getCommentsIdForbidden
*/
type GetCommentsIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCommentsIDForbidden creates GetCommentsIDForbidden with default headers values
func NewGetCommentsIDForbidden() *GetCommentsIDForbidden {

	return &GetCommentsIDForbidden{}
}

// WithPayload adds the payload to the get comments Id forbidden response
func (o *GetCommentsIDForbidden) WithPayload(payload *models.Error) *GetCommentsIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get comments Id forbidden response
func (o *GetCommentsIDForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommentsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCommentsIDNotFoundCode is the HTTP code returned for type GetCommentsIDNotFound
const GetCommentsIDNotFoundCode int = 404

/*GetCommentsIDNotFound Comment not found

swagger:response getCommentsIdNotFound
*/
type GetCommentsIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCommentsIDNotFound creates GetCommentsIDNotFound with default headers values
func NewGetCommentsIDNotFound() *GetCommentsIDNotFound {

	return &GetCommentsIDNotFound{}
}

// WithPayload adds the payload to the get comments Id not found response
func (o *GetCommentsIDNotFound) WithPayload(payload *models.Error) *GetCommentsIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get comments Id not found response
func (o *GetCommentsIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommentsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
