// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CommentList comment list
// swagger:model CommentList
type CommentList struct {

	// data
	Data CommentListData `json:"data"`

	// has after
	HasAfter bool `json:"hasAfter,omitempty"`

	// has before
	HasBefore bool `json:"hasBefore,omitempty"`

	// next after
	NextAfter int64 `json:"nextAfter,omitempty"`

	// next before
	NextBefore int64 `json:"nextBefore,omitempty"`
}

// Validate validates this comment list
func (m *CommentList) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CommentList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommentList) UnmarshalBinary(b []byte) error {
	var res CommentList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
