// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Entry entry
// swagger:model Entry
type Entry struct {

	// author
	Author *User `json:"author,omitempty"`

	// comment count
	CommentCount int64 `json:"commentCount,omitempty"`

	// comments
	Comments *CommentList `json:"comments,omitempty"`

	// content
	Content string `json:"content,omitempty"`

	// created at
	CreatedAt float64 `json:"createdAt,omitempty"`

	// cut content
	CutContent string `json:"cutContent,omitempty"`

	// cut title
	CutTitle string `json:"cutTitle,omitempty"`

	// edit content
	EditContent string `json:"editContent,omitempty"`

	// has cut
	HasCut bool `json:"hasCut,omitempty"`

	// id
	// Minimum: 1
	ID int64 `json:"id,omitempty"`

	// is favorited
	IsFavorited bool `json:"isFavorited,omitempty"`

	// is watching
	IsWatching bool `json:"isWatching,omitempty"`

	// privacy
	Privacy string `json:"privacy,omitempty"`

	// rating
	Rating *Rating `json:"rating,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// visible for
	VisibleFor EntryVisibleFor `json:"visibleFor"`

	// word count
	WordCount int64 `json:"wordCount,omitempty"`
}

// Validate validates this entry
func (m *Entry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthor(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateComments(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePrivacy(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRating(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Entry) validateAuthor(formats strfmt.Registry) error {

	if swag.IsZero(m.Author) { // not required
		return nil
	}

	if m.Author != nil {

		if err := m.Author.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("author")
			}
			return err
		}
	}

	return nil
}

func (m *Entry) validateComments(formats strfmt.Registry) error {

	if swag.IsZero(m.Comments) { // not required
		return nil
	}

	if m.Comments != nil {

		if err := m.Comments.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("comments")
			}
			return err
		}
	}

	return nil
}

func (m *Entry) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.MinimumInt("id", "body", int64(m.ID), 1, false); err != nil {
		return err
	}

	return nil
}

var entryTypePrivacyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["all","some","me","anonymous"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		entryTypePrivacyPropEnum = append(entryTypePrivacyPropEnum, v)
	}
}

const (
	// EntryPrivacyAll captures enum value "all"
	EntryPrivacyAll string = "all"
	// EntryPrivacySome captures enum value "some"
	EntryPrivacySome string = "some"
	// EntryPrivacyMe captures enum value "me"
	EntryPrivacyMe string = "me"
	// EntryPrivacyAnonymous captures enum value "anonymous"
	EntryPrivacyAnonymous string = "anonymous"
)

// prop value enum
func (m *Entry) validatePrivacyEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, entryTypePrivacyPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Entry) validatePrivacy(formats strfmt.Registry) error {

	if swag.IsZero(m.Privacy) { // not required
		return nil
	}

	// value enum
	if err := m.validatePrivacyEnum("privacy", "body", m.Privacy); err != nil {
		return err
	}

	return nil
}

func (m *Entry) validateRating(formats strfmt.Registry) error {

	if swag.IsZero(m.Rating) { // not required
		return nil
	}

	if m.Rating != nil {

		if err := m.Rating.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rating")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Entry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Entry) UnmarshalBinary(b []byte) error {
	var res Entry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
