// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetAccountInvitesOKBody get account invites o k body
// swagger:model getAccountInvitesOKBody
type GetAccountInvitesOKBody struct {

	// invites
	Invites []string `json:"invites"`
}

// Validate validates this get account invites o k body
func (m *GetAccountInvitesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInvites(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetAccountInvitesOKBody) validateInvites(formats strfmt.Registry) error {

	if swag.IsZero(m.Invites) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetAccountInvitesOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetAccountInvitesOKBody) UnmarshalBinary(b []byte) error {
	var res GetAccountInvitesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
