// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Profile profile
// swagger:model Profile
type Profile struct {
	Friend

	ProfileAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Profile) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Friend
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Friend = aO0

	// AO1
	var aO1 ProfileAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.ProfileAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Profile) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Friend)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.ProfileAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this profile
func (m *Profile) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Friend
	if err := m.Friend.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with ProfileAllOf1
	if err := m.ProfileAllOf1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Profile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Profile) UnmarshalBinary(b []byte) error {
	var res Profile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
